name: Publish and Deploy Docker image

on:
  push:
    branches:
      - github-actions

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: 977977/mindly-care

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mindly-care:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy_on_linode:
    name: Run update script via ssh to pull and update container
    needs: "push_to_docker_hub"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: ${{ secrets.LINODE_PORT }}
          script: |
            echo "Reached Linode Server from GitHub Actions"
            pwd
            sh deploy.sh
